# Generated by Django 5.0 on 2023-12-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options_alter_user_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_oauth_registered',
            field=models.BooleanField(default=False),
        ),
    ]
