# Generated by Django 5.0 on 2024-01-12 09:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_paymentmethod_user_watchlist_address_bkashpayment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bkashpayment',
            name='phone_number',
            field=models.CharField(help_text='Enter a valid Bangladeshi phone number. (e.g., 017XXXXXXXX)', max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid Bangladeshi phone number.', regex='^(?:\\+88)?01[3-9]\\d{8}$')]),
        ),
    ]
