# Generated by Django 5.0 on 2024-01-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_bkashpayment_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardpayment',
            name='card_name',
            field=models.CharField(default='John Doe', max_length=256),
        ),
    ]
