# Generated by Django 5.0 on 2024-01-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_cardpayment_card_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='previous_email',
            field=models.EmailField(default=None, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='bkashpayment',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='cardpayment',
            name='card_name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='cardpayment',
            name='card_number',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='cardpayment',
            name='cvc_code',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='cardpayment',
            name='expiration_date',
            field=models.CharField(max_length=7),
        ),
    ]
