# Generated by Django 4.2.7 on 2023-12-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(default='listings/empty-item.png', max_length=250, upload_to='listings/'),
        ),
    ]
