# Generated by Django 4.2.7 on 2023-12-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_listing_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(default='listings/placeholder-image.png', max_length=250, upload_to='listings/'),
        ),
    ]
