# Generated by Django 4.2.7 on 2023-12-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_listing_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='buying_format',
            field=models.CharField(choices=[('A', 'Auction'), ('BIN', 'Buy It Now'), ('AO', 'Accept Offer')], default='A', max_length=250),
        ),
        migrations.AddField(
            model_name='listing',
            name='condition',
            field=models.CharField(choices=[('N', 'New'), ('G_R', 'Good - Refurbished'), ('U', 'Used')], default='G_R', max_length=250),
        ),
        migrations.AddField(
            model_name='listing',
            name='free_shipping',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='local_pickup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='location',
            field=models.CharField(choices=[('D', 'Dhaka'), ('C', 'Chittagong'), ('R', 'Rajshahi'), ('K', 'Khulna'), ('B', 'Barisal'), ('S', 'Sylhet'), ('RG', 'Rangpur'), ('M', 'Mymensing')], default='D', max_length=250),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('F', 'Fashion'), ('T', 'Toys'), ('E', 'Electronics'), ('H', 'Home'), ('O', 'Others')], default='O', max_length=250),
        ),
    ]
