# Generated by Django 4.2.7 on 2023-12-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing_buying_format_listing_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.URLField(default='https://developers.elementor.com/docs/assets/img/elementor-placeholder-image.png'),
        ),
    ]
