# Generated by Django 5.0 on 2023-12-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_listing_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='condition',
            field=models.CharField(choices=[('N', 'New'), ('GR', 'Good - Refurbished'), ('U', 'Used')], default='GR', max_length=250),
        ),
    ]
