# Generated by Django 5.0 on 2023-12-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_listing_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='condition',
            field=models.CharField(choices=[('N', 'New'), ('G_R', 'Good - Refurbished'), ('U', 'Used')], default='G_R', max_length=250),
        ),
    ]
