# Generated by Django 5.0 on 2023-12-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_listing_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(default='listings/placeholder-image.png', max_length=250, upload_to='listings/'),
        ),
    ]
