# Generated by Django 5.0 on 2024-01-12 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_bid_bid_by_delete_address'),
        ('users', '0008_alter_bkashpayment_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='payment_method',
            field=models.ForeignKey(default=71, on_delete=django.db.models.deletion.CASCADE, related_name='bid', to='users.paymentmethod'),
        ),
    ]
